baseurl = "https://www.perlin-ir.org/"
languageCode = "en-us"
title = "Perlin - Information Retrieval"
theme = "hugo-lithium-theme"
PygmentsCodeFences = true
pygmentsstyle = "native"

[[menu.main]]
    name = "Documentation"
    url = "https://doc.perlin-ir.org/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/JDemler/perlin"

[params]
    description = "Perlin is a lazy, zero-allocation and data-agnostic Information Retrieval library"